name: Update Changelog

on:
  push:
    branches:
      - main
    paths:
      - RELEASE_NOTES.md

permissions: write-all

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepend RELEASE_NOTES to CHANGELOG
        run: |
          if [ ! -f CHANGELOG.md ]; then
            touch CHANGELOG.md
          fi

          cat RELEASE_NOTES.md > /tmp/TEMP_CHANGELOG.md
          echo -e "\n\n---\n" >> /tmp/TEMP_CHANGELOG.md
          cat CHANGELOG.md >> /tmp/TEMP_CHANGELOG.md
          mv /tmp/TEMP_CHANGELOG.md CHANGELOG.md

      - name: Commit updated CHANGELOG
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add CHANGELOG.md
          git commit -m "Update CHANGELOG from RELEASE_NOTES" || echo "No changes"
          git push